name: http_with_flutter
description: "HTTP bilan flutter ilova"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  d_navigation_bar: ^0.0.1
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  zoom_tap_animation: ^1.1.0
  hive: ^2.2.3
  loading_animation_widget: ^1.2.1
  flutter_carousel_widget: ^2.2.0
  smooth_page_indicator: ^1.1.0
  path_provider: ^2.1.3
  speech_to_text: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/img/
    - assets/icons/connection_window_icons/
    - assets/icons/profile_icons/
